version: '3.8'

services:
  api:
    build:
      context: .
      target: api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ai_service
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - OLLAMA_API_URL=http://ollama:11434
      - PYTHONPATH=/app
    depends_on:
      - db
      - ollama
    volumes:
      - .:/app
      # Create a volume for pip cache to speed up reinstalls
      - pip_cache:/root/.cache/pip
    # Override the CMD to watch for requirement changes
    command: >
      sh -c "sleep 10 &&  # Give Ollama more time to start
             chmod +x scripts/init_ollama.sh &&
             ./scripts/init_ollama.sh &&
             pip install -r requirements.txt &&
             python run.py"

  ollama:
    build:
      context: .
      target: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  pip_cache:
  ollama_data: 